[toolchain]
channel = "1.77.1"
components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rustc",
    "rustfmt",
]
targets = [ "x86_64-unknown-linux-musl", "x86_64-unknown-linux-musl" ]
profile = "minimal"
